version: "3.9"
services:
  db:
    image: postgres:16
    container_name: plantilla_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbplantilla
      POSTGRES_PASSWORD: dbplantilla
      POSTGRES_DB: dbplantilla
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: